spring:
  application:
    name: Invoice mock
  security:
    user:
      name: admin
      password: admin123

server:
  servlet:
    context-path: /api/v1
  port: 9090
  address: 0.0.0.0

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.knp.invoice_mock: DEBUG
